### ISSUE TITLE
Multiple benchmark set support is inconsistent, bound_label doesn't seem to work

### ISSUE THREAD

**Issue by NickCH-K** [nlapier2/PySensemakr#40]
Several issues as I put together a coding example with the package, having to do with multiple sets of benchmark covariates, and the use of labels for the benchmark sets. All start from the example Darfur code:

```python
import sensemakr as smkr
import statsmodels.formula.api as smf
darfur = smkr.load_darfur()
reg_model = smf.ols(formula='peacefactor ~ directlyharmed + age + farmer_dar + herder_dar + '\
                    'pastvoted + hhsize_darfur + female + village', data=darfur)
darfur_model = reg_model.fit()
```

1. The `bound_label` argument doesn't seem to do anything (note this is the same whether I do `['a']` or `'a'`):

```python
darfur_sense = smkr.Sensemakr(model = darfur_model,
                              treatment = "directlyharmed",
                              benchmark_covariates = ['female'],
                              bound_label=['a'])
# Label is '1x female'
darfur_sense.summary()
# Label is '1x female'
darfur_sense.plot()
```

2. Benchmark sets *can* be labeled by passing a named `dict` of string lists, but this is undocumented.

```python
darfur_sense = smkr.Sensemakr(model = darfur_model,
                              treatment = "directlyharmed",
                              benchmark_covariates = {'a':['female']})
# Label is '1x a'
darfur_sense.summary()
# Label is '1x a'
darfur_sense.plot()
```

3. There is support for multiple sets of benchmarks by passing a list of lists (similar to a named list of vectors in the R version) or a named `dict` but this is undocumented, and also this only works for `.summary()`, not `.plot()`

```python
darfur_sense = smkr.Sensemakr(model = darfur_model,
                              treatment = "directlyharmed",
                              benchmark_covariates = [['female'],
                                                      ['pastvoted','female']])
# Works fine
darfur_sense.summary()
# Error "AttributeError: 'Series' object has no attribute 'append'"
darfur_sense.plot()
```

Results are the same if using `{'a':['female'], 'b':['pastvoted','female']}` instead of  `[['female'], ['pastvoted','female']]`

**Comment by carloscinelli** [comment]
Hi @NickCH-K thanks so much for bringing these here! Keep them coming!
@KennyZhang-17 can you take a look at it?

**Comment by KennyZhang-17** [comment]
Thanks for pointing these out @NickCH-K!  We could definitely document the benchmark_covariates better. The error raised in (3) plot seems due to the deprecation of append method in pandas 2.0 or newer. It should be relatively easy for me to fix this by replacing append with the concat (I will reply to this once a newer version is coming out). 

The bound label issue in (1) is more complicated. The "bound label" argument is mainly for the use of defining the sensemakr object without a good benchmark covariate name (defining with r2dyz.x for example). In the case where we already have bound labels like "1x ['female']", "2x ['female']", "1x ['pastvoted', 'female']", it would be ambiguous which one to replace with (maybe a dimension check could help).  For now, the labels can be changed if you go to darfur_sense.bounds and change the bound_label manually (or alternatively using a named dict as in (2)). I think a similar phenomena can be observed in R (@carloscinelli) with:

> data("darfur")
> # runs regression model
> model <- lm(peacefactor ~ directlyharmed + age + farmer_dar + herder_dar +
+                 pastvoted + hhsize_darfur + female + village, data = darfur)
sensitivity <- sensemakr(model, treatment = "directlyharmed",
+                                                    benchmark_covariates = "female",
+                                                    kd = 1:3, bound_label='a')
> plot(sensitivity)

**Comment by NickCH-K** [comment]
Thank you! I will go ahead with the example for now and cross my fingers for the multiple-benchmark plot working by the time it's relevant.

**Comment by carloscinelli** [comment]
- [ ] (1) improve documentation of "bound_label" argument, it should explicitly mention it is intended to only provide labels for bounds provided manually; maybe include a warning if "bound_label" is provided without a manual bound, such as "no manual bound provided, bound_label ignored;"
- [ ] (2) document the use of dictionaries for multiple benchmarks; this should be the preferred approach, where you can provide easily provide names to the benchmarks.
- [ ] (3) document the use of lists of lists for multiple benchmarks and fix the plot. But we should comment that the preferred approach is (2).

**Comment by carloscinelli** [comment]
@NickCH-K you can already do multiple benchmarks using dictionaries, and it should be working. We will fix the bug on the list of lists use and also document it, but personally I would use dictionaries when doing multiple benchmarks, it is cleaner.

**Comment by NickCH-K** [comment]
Thank you! I like the dict syntax best anyway. Once it updates I will try it again to see if the plotting works.

**Comment by NickCH-K** [comment]
Fantastic! Thank you very much.
